# Generated by Django 4.1 on 2023-01-19 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFunctional', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelpost',
            name='image',
        ),
        migrations.AlterField(
            model_name='modelpost',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2023, 1, 19, 9, 47, 6, 693292, tzinfo=datetime.timezone.utc)),
        ),
    ]
