# Generated by Django 4.1 on 2023-01-19 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFunctional', '0003_alter_modelpost_time_modelposteo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpost',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2023, 1, 19, 9, 58, 11, 254314, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='modelposteo',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2023, 1, 19, 9, 58, 11, 255312, tzinfo=datetime.timezone.utc)),
        ),
    ]
