# Generated by Django 4.1 on 2023-01-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFunctional', '0004_alter_modelpost_time_alter_modelposteo_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='modelPost',
        ),
        migrations.AlterField(
            model_name='modelposteo',
            name='Time',
            field=models.TimeField(),
        ),
    ]
