# Generated by Django 4.1 on 2023-01-19 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFunctional', '0005_delete_modelpost_alter_modelposteo_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelposteo',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 19, 10, 3, 58, 856427, tzinfo=datetime.timezone.utc)),
        ),
    ]
