# Generated by Django 4.1 on 2023-01-20 11:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appFunctional', '0007_alter_modelposteo_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelposteo',
            name='Field',
            field=ckeditor.fields.RichTextField(max_length=1000),
        ),
    ]
