# Generated by Django 4.1 on 2023-01-21 21:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appFunctional', '0011_modelposteohtml'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='modelPosteo',
            new_name='modelPosteoPython',
        ),
    ]
